### ISSUE TITLE
Support for Arrays of Link Objects

### ISSUE THREAD

**Issue by JolandaVerhoef** [Nykredit/jackson-dataformat-hal#2]
According to the HAL Spec, a HAL Link can either be a Link object, or an array of Link objects (https://tools.ietf.org/html/draft-kelly-json-hal-08#section-4.1.1).

It seems that the library does not offer support for these arrays yet.

**Comment by langecode** [comment]
Thank you for the feedback. I expect to update the documentation as soon as there is a little time for it. This is actually supported (both for serialization and deserialization) - but not shown in the README currently.

To have an array of links, all you need to do is annotate a collection of `HALLink` with the `@Link` annotation. E.g.,

```java
@Link
Collection<HALLink> customers;
```

This should give an output as
```json
{
  "_links": {
    "customers": [ ]
  }
}
```

You may then initialize the collection with any specific collection you see fit :-)
