### ISSUE TITLE
Dependency from deprecated jackson-jaxrs-json-provider

### ISSUE THREAD

**Issue by meden** [Nykredit/jackson-dataformat-hal#4]
Hello,

I noticed that `jackson-dataformat-hal` depends on deprecated module `jackson-jaxrs-json-provider` [1]. Maybe should be replaced with `jackson-jaxrs-providers`.

Thanks for your work!

[1] https://github.com/FasterXML/jackson-jaxrs-json-provider/blob/master/README.md

**Comment by langecode** [comment]
Thanks for notifying and a good point. I will look at updating this.

**Comment by langecode** [comment]
Fixed for version 1.0.1
