### ISSUE TITLE
Generic naming

### ISSUE THREAD

**Issue by haasted** [Nykredit/jackson-dataformat-hal#6]
The name of the annotation `Resource` is rather generic. Any chance that it could be renamed to something more specific to its usage, e.g. `HALResource`?

**Comment by langecode** [comment]
Well, I know it clashes with the EJB resource annotation (which is of course an entirely different semantic). However while it does indicate a HAL resource `Resource` seemed the most simple naming and it is scoped by the Java packages also.

We are in a dialog with guys from the JAX-RS specification team about supporting HAL directly in the specification. This might, of course, change the annotations altogether however I would like to keep it as-is for now.
